image: kirinnee/frontend-gitlab-runner

cache:
  paths:
    - obj/**/*.*

Build:
  script:
    - cd Narwhal.Lib
    - dotnet pack -c=Release -o=output
    - cd output
    - dotnet nuget push *.nupkg -k $NUGET_SECRET -s https://api.nuget.org/v3/index.json
  only:
    - master
